/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    posts: Post;
    faqs: Faq;
    testimonials: Testimonial;
    'contact-queries': ContactQuery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-queries': ContactQueriesSelect<false> | ContactQueriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images once and reuse them throughout the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text used for accessibility and SEO.
   */
  alt: string;
  /**
   * Optional image caption.
   */
  caption?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  cloudinaryVersion?: number | null;
  /**
   * Direct URL to the original file without transformations
   */
  originalUrl?: string | null;
  /**
   * URL with applied transformations
   */
  transformedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      cloudinaryResourceType?: string | null;
      cloudinaryFormat?: string | null;
      cloudinaryVersion?: number | null;
      /**
       * Direct URL to the original file without transformations
       */
      originalUrl?: string | null;
      /**
       * URL with applied transformations
       */
      transformedUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      /**
       * File size in bytes
       */
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      cloudinaryResourceType?: string | null;
      cloudinaryFormat?: string | null;
      cloudinaryVersion?: number | null;
      /**
       * Direct URL to the original file without transformations
       */
      originalUrl?: string | null;
      /**
       * URL with applied transformations
       */
      transformedUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      /**
       * File size in bytes
       */
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      cloudinaryResourceType?: string | null;
      cloudinaryFormat?: string | null;
      cloudinaryVersion?: number | null;
      /**
       * Direct URL to the original file without transformations
       */
      originalUrl?: string | null;
      /**
       * URL with applied transformations
       */
      transformedUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      /**
       * File size in bytes
       */
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      cloudinaryResourceType?: string | null;
      cloudinaryFormat?: string | null;
      cloudinaryVersion?: number | null;
      /**
       * Direct URL to the original file without transformations
       */
      originalUrl?: string | null;
      /**
       * URL with applied transformations
       */
      transformedUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      /**
       * File size in bytes
       */
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Product categories shown on the website. Only Active categories appear on the frontend.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Optional icon, e.g. 🦄
   */
  emoji?: string | null;
  /**
   * Optional.
   */
  image?: (string | null) | Media;
  description?: string | null;
  /**
   * Optional card gradient classes, e.g. "from-pink/40 to-pink/10".
   */
  tint?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Auto-generated from the title. Edit only if you need a custom URL.
   */
  slug: string;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * Every product must belong to a category. Only Active products appear on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Required — pick the category this product belongs to.
   */
  category: string | Category;
  /**
   * Shown as-is, e.g. ₹349
   */
  price: string;
  /**
   * One-line text used on product cards.
   */
  shortDescription?: string | null;
  /**
   * Full description shown on the product page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Pre-filled WhatsApp message. Leave blank to use: "Hi! I’d like to order: <product> (<price>)."
   */
  whatsappMessage?: string | null;
  /**
   * Main image used on cards, listings and social previews.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Optional extra images shown on the product page.
   */
  gallery?: (string | Media)[] | null;
  /**
   * Optional /public path used when no featured image is uploaded, e.g. /images/p-unicorn.jpg
   */
  imagePath?: string | null;
  colors?:
    | {
        /**
         * Hex, e.g. #FF8FB8
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  sizes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Auto-generated from the title. Edit only if you need a custom URL.
   */
  slug: string;
  status: 'active' | 'inactive';
  /**
   * Show in the "Best-selling" section on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles. Only Active posts appear on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  author?: string | null;
  cover?: (string | null) | Media;
  /**
   * Optional /public path, e.g. /images/g1.jpg
   */
  coverPath?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated from the title. Edit only if you need a custom URL.
   */
  slug: string;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions shown in the FAQ section (also used for FAQ rich results in Google).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  q: string;
  a: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews shown on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  /**
   * e.g. Mom of two, Pune
   */
  role: string;
  text: string;
  /**
   * Initials shown in the circle, e.g. AS
   */
  avatar?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted through the website contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-queries".
 */
export interface ContactQuery {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-queries';
        value: string | ContactQuery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  cloudinaryVersion?: T;
  originalUrl?: T;
  transformedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              cloudinaryResourceType?: T;
              cloudinaryFormat?: T;
              cloudinaryVersion?: T;
              originalUrl?: T;
              transformedUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              cloudinaryResourceType?: T;
              cloudinaryFormat?: T;
              cloudinaryVersion?: T;
              originalUrl?: T;
              transformedUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              cloudinaryResourceType?: T;
              cloudinaryFormat?: T;
              cloudinaryVersion?: T;
              originalUrl?: T;
              transformedUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              cloudinaryResourceType?: T;
              cloudinaryFormat?: T;
              cloudinaryVersion?: T;
              originalUrl?: T;
              transformedUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  emoji?: T;
  image?: T;
  description?: T;
  tint?: T;
  order?: T;
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  price?: T;
  shortDescription?: T;
  description?: T;
  whatsappMessage?: T;
  featuredImage?: T;
  gallery?: T;
  imagePath?: T;
  colors?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  rating?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  slug?: T;
  status?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  date?: T;
  author?: T;
  cover?: T;
  coverPath?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  q?: T;
  a?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  text?: T;
  avatar?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-queries_select".
 */
export interface ContactQueriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * All content shown on the website home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroBadge?: string | null;
  heroTitle: string;
  heroSubtitle: string;
  heroButtonText?: string | null;
  /**
   * Leave blank to open WhatsApp with a pre-filled message.
   */
  heroButtonLink?: string | null;
  heroSecondaryButtonText?: string | null;
  heroSecondaryButtonLink?: string | null;
  /**
   * Main hero image.
   */
  heroImage?: (string | null) | Media;
  heroImages?: (string | Media)[] | null;
  heroStatsText?: string | null;
  categoriesSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  featuredSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  whyChooseSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  whyChoose?:
    | {
        icon?: string | null;
        title: string;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  howItWorksSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  steps?:
    | {
        n?: string | null;
        title: string;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  gallerySection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  galleryImages?: (string | Media)[] | null;
  testimonialsSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  faqSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Optional part of the heading shown in the brand colour.
     */
    highlight?: string | null;
    description?: string | null;
  };
  kitEyebrow?: string | null;
  kitHeading?: string | null;
  kitDescription?: string | null;
  kitItems?:
    | {
        i?: string | null;
        t: string;
        id?: string | null;
      }[]
    | null;
  kitImage?: (string | null) | Media;
  kitButtonText?: string | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  ctaButtonText?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * All content shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  heading: string;
  description: string;
  bannerImage?: (string | null) | Media;
  /**
   * Fallback /public path used when no banner image is uploaded.
   */
  bannerImagePath?: string | null;
  stats?:
    | {
        /**
         * e.g. 10k+
         */
        value: string;
        /**
         * e.g. Happy kids
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  buttonText?: string | null;
  missionHeading?: string | null;
  mission?: string | null;
  visionHeading?: string | null;
  vision?: string | null;
  extraSections?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Company details, contact information, social links and branding used across the whole website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  companyName: string;
  /**
   * Appended to the browser title on the home page.
   */
  tagline?: string | null;
  description: string;
  footerText?: string | null;
  phone: string;
  /**
   * Digits only, including country code (e.g. 919354081946).
   */
  whatsapp: string;
  email: string;
  workingHours?: string | null;
  address?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  ogImage?: (string | null) | Media;
  /**
   * Used for canonical URLs, sitemap and structured data.
   */
  url: string;
  locale?: string | null;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroButtonText?: T;
  heroButtonLink?: T;
  heroSecondaryButtonText?: T;
  heroSecondaryButtonLink?: T;
  heroImage?: T;
  heroImages?: T;
  heroStatsText?: T;
  categoriesSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  featuredSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  whyChooseSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  whyChoose?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  howItWorksSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  steps?:
    | T
    | {
        n?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  gallerySection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  galleryImages?: T;
  testimonialsSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  faqSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        description?: T;
      };
  kitEyebrow?: T;
  kitHeading?: T;
  kitDescription?: T;
  kitItems?:
    | T
    | {
        i?: T;
        t?: T;
        id?: T;
      };
  kitImage?: T;
  kitButtonText?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  ctaButtonText?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  bannerImage?: T;
  bannerImagePath?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  buttonText?: T;
  missionHeading?: T;
  mission?: T;
  visionHeading?: T;
  vision?: T;
  extraSections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  description?: T;
  footerText?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  workingHours?: T;
  address?: T;
  facebook?: T;
  instagram?: T;
  linkedin?: T;
  youtube?: T;
  logo?: T;
  favicon?: T;
  ogImage?: T;
  url?: T;
  locale?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}